-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Plantiful.Object exposing (CheckIn(..), CreateCheckInPayload(..), CreateGardenPayload(..), CreatePlantPayload(..), Garden(..), Plant(..), SignInPayload(..), SignOutPayload(..), User(..))


type CheckIn
    = CheckIn


type CreateCheckInPayload
    = CreateCheckInPayload


type CreateGardenPayload
    = CreateGardenPayload


type CreatePlantPayload
    = CreatePlantPayload


type Garden
    = Garden


type Plant
    = Plant


type SignInPayload
    = SignInPayload


type SignOutPayload
    = SignOutPayload


type User
    = User
