-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Plantiful.ScalarCodecs exposing (Id, codecs)

import Json.Decode as Decode exposing (Decoder)
import Plantiful.Scalar exposing (defaultCodecs)


type alias Id =
    Plantiful.Scalar.Id


codecs : Plantiful.Scalar.Codecs Id
codecs =
    Plantiful.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
