-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Plantiful.Object.CreateGardenPayload exposing (clientMutationId, errors, garden, success)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Plantiful.InputObject
import Plantiful.Interface
import Plantiful.Object
import Plantiful.Scalar
import Plantiful.ScalarCodecs
import Plantiful.Union


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) Plantiful.Object.CreateGardenPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


errors : SelectionSet (Maybe (List String)) Plantiful.Object.CreateGardenPayload
errors =
    Object.selectionForField "(Maybe (List String))" "errors" [] (Decode.string |> Decode.list |> Decode.nullable)


garden :
    SelectionSet decodesTo Plantiful.Object.Garden
    -> SelectionSet decodesTo Plantiful.Object.CreateGardenPayload
garden object_ =
    Object.selectionForCompositeField "garden" [] object_ identity


success : SelectionSet Bool Plantiful.Object.CreateGardenPayload
success =
    Object.selectionForField "Bool" "success" [] Decode.bool
