-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Plantiful.Object.CreateCheckInPayload exposing (checkIn, clientMutationId, errors, success)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Plantiful.InputObject
import Plantiful.Interface
import Plantiful.Object
import Plantiful.Scalar
import Plantiful.ScalarCodecs
import Plantiful.Union


checkIn :
    SelectionSet decodesTo Plantiful.Object.CheckIn
    -> SelectionSet decodesTo Plantiful.Object.CreateCheckInPayload
checkIn object_ =
    Object.selectionForCompositeField "checkIn" [] object_ identity


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) Plantiful.Object.CreateCheckInPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


errors : SelectionSet (Maybe (List String)) Plantiful.Object.CreateCheckInPayload
errors =
    Object.selectionForField "(Maybe (List String))" "errors" [] (Decode.string |> Decode.list |> Decode.nullable)


success : SelectionSet Bool Plantiful.Object.CreateCheckInPayload
success =
    Object.selectionForField "Bool" "success" [] Decode.bool
