-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Plantiful.Object.Plant exposing (addedBy, checkFrequencyScalar, checkFrequencyUnit, garden, id, name, notes)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Plantiful.InputObject
import Plantiful.Interface
import Plantiful.Object
import Plantiful.Scalar
import Plantiful.ScalarCodecs
import Plantiful.Union


addedBy :
    SelectionSet decodesTo Plantiful.Object.User
    -> SelectionSet decodesTo Plantiful.Object.Plant
addedBy object_ =
    Object.selectionForCompositeField "addedBy" [] object_ identity


checkFrequencyScalar : SelectionSet Int Plantiful.Object.Plant
checkFrequencyScalar =
    Object.selectionForField "Int" "checkFrequencyScalar" [] Decode.int


checkFrequencyUnit : SelectionSet String Plantiful.Object.Plant
checkFrequencyUnit =
    Object.selectionForField "String" "checkFrequencyUnit" [] Decode.string


garden :
    SelectionSet decodesTo Plantiful.Object.Garden
    -> SelectionSet decodesTo Plantiful.Object.Plant
garden object_ =
    Object.selectionForCompositeField "garden" [] object_ identity


id : SelectionSet Plantiful.ScalarCodecs.Id Plantiful.Object.Plant
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Plantiful.ScalarCodecs.codecs |> Plantiful.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Plantiful.Object.Plant
name =
    Object.selectionForField "String" "name" [] Decode.string


notes : SelectionSet (Maybe String) Plantiful.Object.Plant
notes =
    Object.selectionForField "(Maybe String)" "notes" [] (Decode.string |> Decode.nullable)
