-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Plantiful.Object.User exposing (authenticationToken, email, firstName, id, lastName)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Plantiful.InputObject
import Plantiful.Interface
import Plantiful.Object
import Plantiful.Scalar
import Plantiful.ScalarCodecs
import Plantiful.Union


authenticationToken : SelectionSet String Plantiful.Object.User
authenticationToken =
    Object.selectionForField "String" "authenticationToken" [] Decode.string


email : SelectionSet String Plantiful.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


firstName : SelectionSet String Plantiful.Object.User
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


id : SelectionSet Plantiful.ScalarCodecs.Id Plantiful.Object.User
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Plantiful.ScalarCodecs.codecs |> Plantiful.Scalar.unwrapCodecs |> .codecId |> .decoder)


lastName : SelectionSet String Plantiful.Object.User
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string
